# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &default
  pop_id: 30
  data_only: true
  language: en
  urls:
    apple_store: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewTop?
    apple_lookup: https://itunes.apple.com/lookup?
  headers:
    accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    user_agent: "iTunes/11.1.1 (Windows; Microsoft Windows 7 x64 Ultimate Edition Service Pack 1 (Build 7601)) AppleWebKit/536.30.1"
    accept_encoding: "gzip, deflate, sdch"
    accept_language: "en-US,en;q=0.8,lv;q=0.6"
    cache_control: "max-age=0"
    x_apple_store_front: "143441­1,17"

development:
  <<: *default
  secret_key_base: 68a17df7db9c98ff3797f26ef9104269972fe07eb3f27efcfedd7e12277435a7d10903f3c6c5539d0c8cb23168e917e47b5ac67a44aa42de4d98c8933258b99a

test:
  <<: *default
  secret_key_base: e7c87552c4feaefa834b9d8228ce3ee2ab9c64ced3cfd362cf5dc448098a96db2cdc60a2d2d392d89771a5dc9963df0ca176101117422cba0c8151baa18334dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
